navikt/tiltaksgjennomforing-api

src/main/java/no/nav/tag/tiltaksgjennomforing/controller/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/controller/TilgangskontrollUtils.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Rolle.java, src/test/java/no/nav/tag/tiltaksgjennomforing/AvtaleControllerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/AvtaleRepositoryTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/controller/TilgangskontrollUtilsTest.java
Tilgjengelig på `/{avtaleId}/rolle`.
=> TAG-211: Endepunkt som returnerer hvilken rolle bruker har på en avtale

src/main/java/no/nav/security/oidc/test/support/FileResourceRetriever.java, src/main/java/no/nav/security/oidc/test/support/JwtTokenGenerator.java, src/main/java/no/nav/security/oidc/test/support/spring/TokenGeneratorConfiguration.java, src/main/java/no/nav/security/oidc/test/support/spring/TokenGeneratorController.java, src/main/resources/application-dev.yaml, src/main/resources/metadata-isso.json, src/main/resources/metadata-selvbetjening.json, src/test/java/no/nav/security/oidc/filter/TokenRetrieverTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/controller/TilgangskontrollUtilsTest.java
Problemet var at iss-localhost stod som issuer på alle utgitte tokens. Nå gir vi ut både tokens med isso og tokens med selvbetjening som issuer.
=> Tag 225 Støtte for flere issuers ved lokal kjøring

pom.xml, src/main/java/no/nav/security/oidc/test/support/spring/TokenGeneratorController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/DevOidcConfiguration.java, src/main/resources/application-prod.yaml, system.properties
Appen går mot Postgres-database, men har falsk innlogging som på localhost.
=> TAG-192 Deploy til Heroku

src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/EndreAvtale.java, src/main/resources/db/migration/V1__init.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/TestData.java
- Endret startDatoTidspunkt til 'startDato'.
- Gjort om fra LocalDateTime til LocalDate og sql-type fra timestamp til date.
=> Tag 272 start dato endrenavn

src/main/java/no/nav/security/oidc/test/support/spring/TokenGeneratorController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/controller/InnloggetBrukerController.java
Lokal støtte for begge innloggingsregimer (ID-porten og NAV).
=> TAG-284 Innloggingslinje

src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/OpprettAvtale.java, src/test/java/no/nav/tag/tiltaksgjennomforing/controller/AvtaleControllerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/TestData.java
Bedriftsnavn blir lagt til ved opprettelse av avtale sammen med deltaker og veileder fnr.
=> Lagt til bedriftNavn i avtale opprettelse

src/main/java/no/nav/tag/tiltaksgjennomforing/controller/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Arbeidsgiver.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Avtalepart.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Deltaker.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Veileder.java, src/main/resources/config/application-dev.yaml, src/main/resources/config/application-testdata.yaml, src/main/resources/db/testdata/V1000__testdata.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/ArbeidsgiverTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/AvtalepartTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/DeltakerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/VeilederTest.java
Funksjonelle endringer:
- Rekkefølge for hvem som kan godkjenne. Veileder må godkjenne sist.
- Endringer etter godkjenning må oppheves (løses ved dialogboks i denne omgang), og da fjernes andre avtaleparters godkjenning.
- Egen visning av avtale når alle har godkjent.
Må sees i sammenheng med https://github.com/navikt/tiltaksgjennomforing/pull/63
=> TAG-181 TAG-184 TAG-308 Ny flyt ved godkjenning av avtale

pom.xml, src/main/java/no/nav/tag/tiltaksgjennomforing/TilgangUnderPilotering.java, src/main/java/no/nav/tag/tiltaksgjennomforing/TiltaksgjennomforingApplication.java, src/main/java/no/nav/tag/tiltaksgjennomforing/controller/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/controller/InnloggetBrukerController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/controller/TokenUtils.java, src/test/java/no/nav/tag/tiltaksgjennomforing/TilgangUnderPiloteringTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/controller/AvtaleControllerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/controller/TokenUtilsTest.java
Tilgangskontroll kun satt på opprett avtale, siden det er inngangen til løsningen.
Tilgang kan settes ved environment variable `TILTAKSGJENNOMFORING_PILOT_ENABLED=true` og `TILTAKSGJENNOMFORING_PILOT_IDENTER=X123456,Z000111` for å kun gi tilgang til X123456 og Z000111. Hvis disse variablene ikke er satt vil alle ha tilgang, det er altså det samme som `TILTAKSGJENNOMFORING_PILOT_ENABLED=false`.
=> TAG-399: Konfigurasjonstyrt hvem som kan bruke løsningen. 

src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Utils.java, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/domene/UtilsTest.java
Skal vi teste første "pull request" 👍 :) status i oversiktsiden
=> TAG-522 Status på oversiktsiden

src/main/java/no/nav/tag/tiltaksgjennomforing/domene/Veileder.java
Endret feilmelding hvis man som veileder prøver å godkjenne på vegne  av uten at ag har godkjent.
=> Endret feilmelding

src/main/resources/db/migration/V7__oppdatere_godkjent_av_dato.sql
Migreringsscript som oppdaterer de nye godkjenningsfeltene (timestamp) så de er i synk med de gamle boolske feltene. Se forklaring under.
=> Lagt til migreringsscript som oppdater godkjenninger

pom.xml, src/main/java/no/nav/tag/tiltaksgjennomforing/TiltaksgjennomforingApplication.java, src/main/java/no/nav/tag/tiltaksgjennomforing/swagger/SwaggerConfig.java
Swagger blir tilgjengelig på 
.../tiltaksgjennomforing-api/swagger-ui.html
=> Legger inn swagger for enklere testing og dokumentasjon av APIene

src/main/java/no/nav/tag/tiltaksgjennomforing/domene/MetrikkRegistrering.java
Fjernet pilotFylke fra meterRegistry counteren, da prometheus ikke likte at det kom en ny tagg på eksisterende metrikk.
=> Fjernet pilotFylke fra metrikk counteren

pom.xml
- Nyere versjon av Spring Boot
- Flytt dupliserte versjonsnumre til properties.
Løser forhåpentligvis feilen med embedded Kafka som sporadisk feiler under testkjøring: https://github.com/spring-projects/spring-boot/issues/17645
=> Nyere versjon av Spring Boot

src/main/resources/logback-spring.xml
- Loggeren no.nav.vault.jdbc.hikaricp.VaultUtil settes til WARN
=> Logger mindre av VaultUtil

src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetNavAnsatt.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Arbeidstrening.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleFactory.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/EndreAvtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Lonnstilskudd.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/MidlertidigLonnstilskudd.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/OpprettAvtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Tiltakstype.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Tiltaktype.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/VarigLonnstilskudd.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapper.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/InternalAvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/metrikker/MetrikkRegistrering.java, src/main/resources/db/migration/V13__tabeller_arbeidstrening_lonnstilskudd.sql, src/main/resources/db/migration/V14__tabeller_arbeidstrening_lonnstilskudd.sql, src/main/resources/db/testdata/V1000__testdata.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBrukerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapperTest.java
Bygger på endring til JPA: https://github.com/navikt/tiltaksgjennomforing-api/tree/spring-data-jpa
Ikke alt er ferdig ennå, men skal være mulig å registrere både arbeidstreningsavtaler og lønnstilskuddsavtaler nå. Det er mulig å bruke denne branchen for å starte utviklingen fra frontend.
=> TAG-439 Lønnstilskudd

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
Fjernes midlertidig pga. feil med PDL.
=> Fjernet pdl-sjekk midlertidig

src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetSelvbetjeningBruker.java, src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/AltinnTilgangsstyringServiceTest.java, src/test/resources/mappings/altinn_tilgangsstyring.json
Lagt til `@Data` på innloggetSelvbetjeningsbruker slik at vi får med organisasjonene vi får fra altinn til frontend.
Lagt til en ekstra bedrift i mocken.
=> Tag 923 skille innlogging - Lagt til lombokData på innloggetBruker

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnholdRepository.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoering.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapper.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/InternalAvtaleController.java, src/test/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapperTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/journalfoering/InternalAvtaleControllerTest.java
Journalfører nye avtaleversjoner
=> Avtale versjon til journalforing

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Maal.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/MaalKategori.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapper.java, src/main/resources/db/migration/V19__maalkategori_som_enums.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapperTest.java
Ved å bruke enums sikrer vi at ikke andre verdier enn de gyldige kan lagres.
=> TAG-868 Mål lagres som kodeverdi

src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBrukerController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggingService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/BjelleVarselController.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java
Lagt til `@CookieValue` på alle kall som kaller `hentInnloggetBruker`. Gjort om `InnloggingsService` til å ikke kalle Altinn hvis man er deltaker (har sendt med deltaker i cookien `innlogget-part`), istedenfor å kun kalle altinn når man er arbeidsgiver.
=> Lagt til cookie value alle kall og endret strategi for altinn kall

src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/PersondataService.java, src/test/java/no/nav/tag/tiltaksgjennomforing/persondata/PersondataServiceTest.java, src/test/resources/mappings/pdl_gradering.json
Ref: https://nav-it.slack.com/archives/C84H68ESC/p1583326295011300
=> PDL - Lagt til strengt fortrolig utland respons

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/NavIdent.java, src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/enhet/ByEnhetStrategy.java, src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/NavIdentTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/enhet/ByEnhetStrategyTest.java
Sjekker om innlogget bruker er navident før henting av enheter man har tilgang på
=> Fiks av byEnhet-strategi

.github/stale.yml
=> Skru av stalebot pa issues

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvbruttInfo.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java, src/main/resources/db/migration/V23__avbryt_avtale_nye_kolonner.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/VeilederTest.java
Gjort en rebase e. committen til Lars A.
=> Avbryter godkjent avtale

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/EndreAvtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoering.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapper.java, src/main/resources/db/migration/V24__familietilknytning_nye_kolonner.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStrategyTest.java
Lagt til felt for spørsmål og forklaring om det eksisterer familietilknytning mellom arbeidsgiver og deltaker i avtale om lønnstilskudd.
Co-authored-by: Mats Bolstad <mats.bolstad@nav.no>
=> Lagt til felt for familietilknytning for lønnstilskudd

src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBrukerController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/GjenopprettetEvent.java, src/main/java/no/nav/tag/tiltaksgjennomforing/utils/TelefonnummerValidator.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/VeilederTest.java
Co-authored-by: Bjarte Tynning <bjarte.tynning@nav.no>
=> lagt til gjenopprette avtale.

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/EndreAvtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Stillingstype.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoering.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapper.java, src/main/resources/db/migration/V30__stillingstype.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStrategyTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapperTest.java
lagt til mulighet for å angi stillingstype.
=> Stillingstype

nais/naiserator.yaml, src/main/resources/config/application-dev-fss.yaml, src/main/resources/config/application-prod-fss.yaml
Se: https://nav-it.slack.com/archives/C60FFACN5/p1602842967317400
=> Ny loginservice url

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStrategy.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/BeregningLonnstilskuddTest.java
Co-authored-by: Sindre Dahl Løken <sindre.loken@nav.no>
=> Oppdatert beregning paa manedslonn fullstilling

src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBrukerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java
Lagt til sleep 10ms paa test funksjonalitet som asserter tidsendringer opp mot hverandre. 
Slik at testene lyser gront pa win10
=> Lagt til sleep 10ms paa test funksjonalitet.

src/main/resources/config/application-prod-fss.yaml
=> Korrigere norg2-url

src/main/java/no/nav/tag/tiltaksgjennomforing/enhet/VeilarbArenaClient.java
=> Feilkode veilarbarena

src/main/resources/config/application-labs-gcp.yaml
=> Wiremock for VeilarbArena og norg2 i labs-gcp

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java
=> Lagrer status på tilskudd ved oppretting

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddForAvtalePeriode.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddForAvtalePeriodeTest.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java, src/main/resources/db/migration/V41__lonnstilskudd_prosent_tilskudd.sql
Ny kolonne med lønnstilskuddprosent på tilskuddsperioder.
Settes foreløpig til prosenten fra Avtalen.
=> ny kolonne pa tilskuddperiode med lonnstilskuddprosent

src/main/java/no/nav/tag/tiltaksgjennomforing/enhet/Norg2Client.java, src/main/resources/config/application-prod-fss.yaml
=> Rettet opp feil veilarbarena-url i prod. Bedre logging v/norg2-feil

src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/oppgave/OppgaveRequest.java
Beskrivelsen i gosys hadde feil url på avtaler som ble opprettet av arbeidsgiver.
=> endret url fra utside til innside i gosys beskrivelse

src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/altinntilgangsstyring/AltinnTilgangsstyringProperties.java, src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/altinntilgangsstyring/AltinnTilgangsstyringService.java, src/main/resources/config/application-dev-fss.yaml, src/main/resources/config/application-labs-gcp.yaml, src/main/resources/config/application-prod-fss.yaml, src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/AltinnTilgangsstyringServiceTest.java, src/test/resources/config/application-local.yaml, src/test/resources/mappings/altinn_10.json, src/test/resources/mappings/altinn_20.json, src/test/resources/mappings/altinn_ikke_treff.json
Opprettet sommerjobb tilgang (meldingstjeneste) i Altinn
Lagt til altinn serviceCode og serviceEditionCode for sommerjob og sjekker sommerjobb tilgang
Co-authored-by: Mats Bolstad <mats.bolstad@nav.no>
=> Altinn tilganger for sommerjobb

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java, src/main/resources/db/migration/V54__avtale_innhold_gjeldende_fra.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java
Co-authored-by: Sindre Løken <sindre.loken@nav.no>
Co-authored-by: Håvard Myrvold Johannessen <havard.myrvold.johannessen@nav.no>
=> Tidspunkt for ikrafttredelse

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java
14 dagers godkjenningsfrist på tilskuddsperioder for beslutter gjelder nå kun fra tilskuddsperiode nummer to.
=> 14 dagers frist kun fra tilskuddsperiode nr 2

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/EndreTilskuddsberegning.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/RegnUtTilskuddsperioderForAvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java
Co-authored-by: Håvard Myrvold Johannessen <havard.myrvold.johannessen@nav.no>
=> Lagt til Stillingsprosent og Antall dager per uke felt

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnholdType.java, src/main/resources/db/migration/V59__innholdtype.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java
Kan se om versjonen er opprettet som følge av å låse opp avtalen, eller forlenging/forkorting/osv.
=> Type på AvtaleInnhold

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/EndreStillingsbeskrivelse.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/EndreTilskuddsberegning.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/RegnUtTilskuddsperioderForAvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java
Flytting av endre antallDagerPerUke og stillingsprosent fra endre tilskuddsberegning til endre stilling.
=> Flytter endring av stillingsprosent og antallDagerPerUke

src/main/java/no/nav/tag/tiltaksgjennomforing/enhet/VeilarbArenaClient.java, src/test/java/no/nav/tag/tiltaksgjennomforing/enhet/VeilarbArenaClientTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/hendelselogg/LyttPåHendelseTilHendelseloggTest.java
Co-authored-by: Håvard Myrvold Johannessen <havard.myrvold.johannessen@nav.no>
=> Fjernet sjekk på formidlingsgruppe og test

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/ArbeidstreningStartOgSluttDatoStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/MentorStartOgSluttDatoStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/MidlertidigLonnstilskuddStartOgSluttDatoStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/SommerjobbStartOgSluttDatoStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/StartOgSluttDatoStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/VarigLonnstilskuddStartOgSluttDatoStrategy.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/FnrTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/GjeldendeTilskuddsperiodeTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/RegnUtTilskuddsperioderForAvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/SommerjobbStartOgSluttDatoStrategyTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/varsel/kafka/RefusjonKlarConsumerTest.java
Co-authored-by: Mats Bolstad <mats.bolstad@nav.no>
Co-authored-by: Sindre Dahl Løken <sindre.loken@nav.no>
=> Fikset tester og fikset at man kan forlenge avtaler

src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoering.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/InternalAvtaleController.java, src/test/java/no/nav/tag/tiltaksgjennomforing/journalfoering/InternalAvtaleControllerTest.java
Lagt til
- tilskuddsperioder
- familjetilknytting
i data til prosess
=> Lagt til tilskuddsperioder i data til prosess

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/ArbeidstreningStartOgSluttDatoStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/MidlertidigLonnstilskuddStartOgSluttDatoStrategy.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStartOgSluttDatoStrategyTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/RegnUtTilskuddsperioderForAvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java
Co-authored-by: Håvard Myrvold Johannessen <havard.myrvold.johannessen@nav.no>
=> Fikset datofeil med en dag formye

src/main/java/no/nav/tag/tiltaksgjennomforing/datavarehus/AvroTiltakHendelseFabrikk.java, src/main/java/no/nav/tag/tiltaksgjennomforing/datavarehus/DvhMeldingKafkaProdusent.java, src/main/resources/avro/tiltaksgjennomforing.avsc, src/main/resources/config/application-dev-fss.yaml, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/varsel/LagVarselFraAvtaleHendelserTest.java, src/test/resources/config/application-local.yaml
- Oppdateringer for å sende meldinger for mentor og inkluderingstilskudd
- Oppdatering i avro
- Fikser i tester for å nulstille meldinger i database
=> Dvh melding mentor

src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/TokenUtils.java, src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/TokenUtilsTest.java
De byttet også hvilket claim fnr hentes fra.
Se https://nav-it.slack.com/archives/C01DE3M9YBV/p1647867506386019
=> Hent fnr fra loginservice fra pid-claim

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtalepart.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddsperiodeConfig.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoering.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapper.java, src/main/resources/config/application.yaml, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtalepartTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/DeltakerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/InkluderingstilskuddTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStartOgSluttDatoStrategyTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/MentorStartOgSluttDatoStrategyTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/RegnUtTilskuddsperioderForAvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/VeilederTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/enhet/VeilarbArenaClientTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/varsel/LagVarselFraAvtaleHendelserTest.java
Kan nå sette pilot på enhet i tillegg til orgnr.
=> Pilot basert på enhetOppfølging

src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/UtviklerTilgangProperties.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriodeStatus.java, src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/InternalArenaMigreringController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/InternalTilskuddsperiodeController.java, src/main/resources/config/application-dev-fss.yaml, src/main/resources/config/application-prod-fss.yaml, src/main/resources/logback-spring.xml, src/test/java/no/nav/tag/tiltaksgjennomforing/LastInnTestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleArenaMigreringTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/RegnUtTilskuddsperioderForAvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/datavarehus/DvhMeldingFilterTest.java
- Laget metode for å generere tilskuddsperioder på avtale
- Endepunkt for å migrere en avtale
- Endepunkt for å migrere alle lønnstilskuddsavtaler
=> Arena tilskuddsperioder

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Beslutter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/BeslutterTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriodeTest.java
Åpner for godkjenning av tilskuddsperioder for neste år.
=> skrur av sperre for å godkjenning av tilskuddsperioder for neste år

src/main/java/no/nav/tag/tiltaksgjennomforing/datadeling/AvtaleHendelseController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/datadeling/AvtaleHendelseService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/datadeling/InternalAvtaleHendelseController.java
- Lager "entiteter" i databasen for alle avtaler
- Disse blir sendt på kafka-topicsen
- Laget mulighet for "dry run" som sjekker at det blir generert json
=> Populerer den store topicen

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleMinimal.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Beslutter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/datavarehus/AvroTiltakHendelseFabrikk.java
Bruker en spørring som kun gir den dataen som trengs i besluttervisning. Filtrerer vekk avtaler basert på abac-oppslag.
=> Henter minimal data beslutter

src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/InternalArenaMigreringController.java
endepunkt for å finne perioder som har tidligere startdato en forrige løpenummer
=> Endepunkt for å finne bugs oppstått ved forlening

pom.xml, src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/altinntilgangsstyring/AltinnTilgangsstyringService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/TilskuddsperiodeKafkaProducer.java, src/main/java/no/nav/tag/tiltaksgjennomforing/utils/MultiValueMap.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/varsel/LagSmsFraAvtaleHendelseTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/varsel/LagVarselFraAvtaleHendelserTest.java
Startet med små endringer i avhengigheter som reduserte filstørrelsen på jar-filen betraktelig, men gjorde deretter en større oppdatering av spring boot og alle avhengigheter i siste commit.
Siste commit kan isoleres til en egen PR om ønskelig!
=> Oppgradere til spring boot 2.7.10

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java
Fikser hvordan man henter data basert på ulike queryparametrer.
Hvis det ikke er satt en queryparameter i det hele tatt hentes nå ikke hele basen.
=> Fikser problemer med hvilken query som skal kjøres

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Arbeidsgiver.java
Bruk bedriftnummer-queryparameteret dersom det sendes inn.
=> Fiks filtrering på bedriftsnummer for arbeidsgiver

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AdminController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriodeRepository.java, src/test/resources/admin-kall.http, src/test/resources/config/application-local.yaml
Admin endepunkt for å annullere tilskuddsperioder på en avtale før en gitt dato og lage nye perioder med status Behandlet i Arena.
=> endepunkt: annullere tilskuddsperioder og lage nye behandlet i arena

pom.xml, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleMinimalListevisning.java, src/main/java/no/nav/tag/tiltaksgjennomforing/datadeling/AvtaleHendelseService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/AuditLoggingFilter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/CorrelationIdFilter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/CorrelationIdSupplier.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditConsoleLogger.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditEntry.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditKafkaConfiguration.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditKafkaLogger.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditLogger.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditVoidLogger.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/EventType.java, src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/kafka/Topics.java, src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/RefusjonEndretStatusKafkaConsumer.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleApiTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/RefusjonEndretStatusTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/TilskuddsperiodeGodkjentKafkaProducerTest.java
For å logge oppslag i tiltaksgjennomforing
setter vi inn et filter som fanger opp alle
responser som går ut fra appen, dekoder de
dersom de er JSON, og leter opp alle
deltakerFnr vi finner i payloadene.
=> Audit-logging i tiltaksgjennomforing

.github/workflows/codeql.yml
Default kjøring av codeql feiler pga
at den forsøker å kjøre med feil
java-versjon
=> Legg til codeql-workflow

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtalePredicate.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/FilterSok.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/FilterSokRepository.java, src/main/resources/db/migration/V99__filtersok_tabell.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtalePredicateTest.java
Bytter ut queryparameter filtere til å være et post request for å så å genere en hash av det som vil fungere som en id i url'en.
Ikke ferdig - wip.
=> WIP: Filtersøk som en hashet sak i urlen

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/InkluderingstilskuddStrategy.java
Oppdatert maxbeløp til 143 900 ihht: https://www.nav.no/arbeidsgiver/inkluderingstilskudd#hva
Også oppdatert en sjekk som ikke var korrekt, men ble litt reddet av en frontendsjekk....
=> oppdatert maxbeløp for inkluderingstilskudd

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/HendelseType.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/DeltakersGodkjenningOpphevetAvArbeidsgiver.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/DeltakersGodkjenningOpphevetAvVeileder.java, src/main/java/no/nav/tag/tiltaksgjennomforing/datadeling/AvtaleHendelseLytter.java
egene eventer for opphevinger av godkjenninger for å slippe å gjøre masse logikk på det i andre apper
=> opphevet eventer som går på kafka

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/InkluderingstilskuddStrategy.java
* Legge til inkluderingssats for 2024
* Toggle mellom 2023 og 2024 satser basert på sluttdato for avtale
=> feat. Legg til 2024 satser for inkluderingstilskudd

pom.xml
Tar ikke spranget til spring boot 3 helt enda
=> Versjonsbump av json-path og spring-boot

.github/workflows/bygg-og-deploy.yml, pom.xml
Salsa rapporterer sårbarheter på pakker
vi ikke har! Forsøker å sende med vår egen
SBOM for å se om dette hjelper.
=> Legg til SBOM

src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FakeFakeUnleash.java, src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggle.java, src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggleConfig.java, src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggleService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/LagSmsFraAvtaleHendelse.java, src/main/resources/config/application-dev-gcp-labs.yaml, src/test/resources/config/application-dockercompose.yml, src/test/resources/config/application-local.yaml, src/test/resources/config/application-test.yaml
* lagt til 6 fra team-tiltak i unleash whitelist strategy
=> Feat. Unleash toggle for whitelist tlfnr

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtaleopphav.java, src/main/resources/db/migration/V103__avtale_opphav.sql
Skal erstatte opprettetAvArbeidsgiver i tillegg til å dekke nye arena avtaler
=> feat. Introdusere avtale opphav felt

src/main/java/no/nav/tag/tiltaksgjennomforing/arena/controller/ArenaSimulatorController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/job/ArenaAgreementJob.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/logging/ArenaAgreementLoggingAspect.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaAgreementAggregate.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaAgreementMigration.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaAgreementMigrationStatus.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/repository/ArenaAgreementMigrationRepository.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaAgreementProcessingService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaAgreementService.java, src/main/resources/db/migration/V105__arena_agreement_migration.sql
Logging av aktivitet for migrering av avtaler i arena
=> feat. Migrasjonslogg for opprettelse av arena avtaler

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggle.java
=> fix. ArbeidstreningReadonly

src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/acl/AktivitetArenaAclClient.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/acl/AktivitetArenaAclTranslationAktivitetKategori.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/acl/AktivitetArenaAclTranslationRequest.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/hendelse/HendelseAktivietsplanIdRequest.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/hendelse/HendelseAktivitetsplanClient.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/ArenaOrdsArbeidsgiverResponse.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/ArenaOrdsClient.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/ArenaOrdsFnrRequest.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/ArenaOrdsFnrResponse.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/ArenaOrdsTokenClient.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/CachedOrdsToken.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/configuration/HendelseAktivitetsplanProperties.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaAgreementProcessingService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaOrdsService.java, src/main/resources/config/application-dev-fss.yaml, src/main/resources/config/application-prod-fss.yaml, src/test/resources/config/application-local.yaml, src/test/resources/mappings/hendelse-aktivitetsplan.json
Kall til tiltak hendelse aktivitetsplan for å oppdater mapping mellom avtale og aktivitetsplan-id.
=> feat. Oppdater tiltak hendelse aktivitetsplan

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AnnullertGrunn.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleUtlopHandling.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/HendelseType.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Identifikator.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/AnnullertAvSystem.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/AvtaleOpprettetAvArena.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/AvtaleUtloperVarsel.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/jobber/PabegynteAvtalerRyddejobb.java, src/main/java/no/nav/tag/tiltaksgjennomforing/datadeling/AvtaleHendelseLytter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggle.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/LagVarselFraAvtaleHendelser.java, src/test/java/no/nav/tag/tiltaksgjennomforing/LastInnTestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/jobber/PabegynteAvtalerRyddejobbTest.java
* Ryddejobb som kjører kl 00:00 hver dag for å fjerne avtaler som enten er påbegynt eller venter på godkjenning og som ikke har blitt endret på 12 uker.
=> feat. Ryddejobb for å annullere gamle avtaler

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Arbeidsgiver.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Deltaker.java
* Skjule Arena avtaler for deltaker og arbeidsgiver hvis avtalen ikke er inngått.
=> feat. skjule Arena avtaler

src/main/java/no/nav/tag/tiltaksgjennomforing/arena/job/ArenaAgreementJob.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/job/ArenaEventRetryJob.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/kafka/ArenaKafkaConsumer.java, src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggle.java
* Feature toggle for Arena Kafka for å kunne enkelt skru av dersom noe går feil.
* Endret navn på toggel for avtale jobb til camelCase.
=> feat. satt opp feature toggel for Arena Kafka

src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/oppgave/GosysBehandlingstype.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/oppgave/GosysTema.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/oppgave/LagGosysVarselLytter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/oppgave/OppgaveProperties.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/oppgave/OppgaveRequest.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/oppgave/OppgaveVarselService.java, src/main/resources/config/application-dev-fss.yaml, src/test/java/no/nav/tag/tiltaksgjennomforing/varsel/oppgave/OppgaveVarselServiceTest.java
Lag en gosys-melding når VTAO er inngått, i
tillegg til meldingen som sendes ved opprettet
avtale.
=> Gosys-melding ved inngått VTAO-avtale

src/main/java/no/nav/tag/tiltaksgjennomforing/TiltaksgjennomforingApplication.java, src/main/java/no/nav/tag/tiltaksgjennomforing/enhet/veilarboppfolging/VeilarboppfolgingClient.java, src/main/resources/config/application.yaml, src/test/java/no/nav/tag/tiltaksgjennomforing/enhet/veilarboppfolging/VeilaroppfolgingClientTest.java, src/test/resources/config/application-test.yaml
* Fiks også 404-funksjonalitet som ikke virker
* enable retryable i tiltaksgjennomforing
=> Legg til retry på VeilarboppfolgingClient

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleSorterer.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtalepart.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/BedriftNrConverter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Status.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Tiltakstype.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/jobber/AvtalestatusEndretJobb.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/jobber/AvtalestatusManglerJobb.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/service/AvtalestatusService.java, src/main/resources/db/migration/V108__avtale-status.sql, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/MentorTest.java
* Nytt DB-felt for status
* Midlertidig jobb for å sette status på alle avtalene
* Jobb som oppdatere status dersom avtaler skifter status pga dato
Status brukes kun for filtrering enn så lenge.
=> feat. legg til status som et databasefelt

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/jobber/GjeldendeTilskuddsperiodeJobb.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/service/GjeldendeTilskuddsperiodeJobbService.java
Opprett ny jobb for å "bootstrappe" nytt felt
for gjeldende tilskuddsperiode på gamle avtaler.
Denne jobben skal fjernes når databasen er
oppdatert.
Vi ruller langsomt ut denne endringen ved å ikke
kjøre på dagen.
=> gjeldendeTilskuddsperiodeJobb

src/main/java/no/nav/tag/tiltaksgjennomforing/satser/Sats.java
https://trello.com/c/NABpbQC6/1649-ny-sats-inkluderingstilskudd
=> feat. 2025 sats for inkluderingstilskudd

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/jobber/AvtalestatusEndretJobb.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/jobber/GjeldendeTilskuddsperiodeJobb.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/service/GjeldendeTilskuddsperiodeJobbService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoering.java, src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapper.java, src/main/java/no/nav/tag/tiltaksgjennomforing/satser/SatsController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/satser/SatsResponse.java, src/main/resources/config/application.yaml
For VTAO-avtaler mangler vi felter for fadderfornavn, fadderetternavn og tlf, og vtao-satsen var ikke
inkludert
=> Legg til manglende felter i avtale-pdf

src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaMigrationAction.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaCleanUpService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleForkortetEntitet.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleForkortetLytter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/ForkortetGrunn.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/HendelseType.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/AvtaleForkortetAvArena.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/AvtaleForkortetAvVeileder.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/AvtaleForlengetAvArena.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/AvtaleForlengetAvVeileder.java, src/main/java/no/nav/tag/tiltaksgjennomforing/datadeling/AvtaleHendelseLytter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/datavarehus/DvhAvtalehendelseLytter.java, src/main/java/no/nav/tag/tiltaksgjennomforing/metrikker/MetrikkRegistrering.java, src/main/java/no/nav/tag/tiltaksgjennomforing/sporingslogg/LagSporingsloggFraAvtaleHendelser.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/LagVarselFraAvtaleHendelser.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/Varsel.java, src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/notifikasjon/NotifikasjonHendelseLytter.java
Sende avtale forkortet hendelse til Arena dersom avtalen blir avsluttet i migreringen.
=> feat. sende egne hendelser for forkorting og forlenging av avtaler

src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/NavIdentFilter.java
For å kunne følge opp brukerstøttesaker som
angår veiledere, kan vi logge navidenter
som utfører kall i appen.
=> NavIdentFilter

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
Ikke i bruk lengre da arbeidstrening er migrert
og avtaler er ryddet opp i.
=> feat. fjerne arbeidstreningstoggle

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Arbeidsgiver.java
Det er noen kall for min-side arbeidsgiver som har stor utslag i grafana. Vi bør derfor ta en analyse av spørringene for å se om de kan optimaliseres for disse bedriftene.
=> logging. logge om det tar mer enn 10 sek

live-templates/README.md, live-templates/securlog.livetemplate.xml, lombok.config, nais/dev-fss.yaml, nais/dev-gcp-labs.yaml, nais/prod-fss.yaml, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/admin/AdminController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/logging/SecureLog.java, src/main/resources/logback-spring.xml
Litt ulikt hvordan det gjøres her:
https://docs.nais.io/observability/logging/how-to/enable-secure-logs/
=> Securelogs

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Arbeidsgiver.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java
OpprettMentorAvtale extender OpprettAvtale, så da vil samme kodesti fungere for begge typer.
=> Fjern overflødig metode opprettMentorAvtale

src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggingService.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java, src/main/java/no/nav/tag/tiltaksgjennomforing/exceptions/ApiExceptionHandler.java, src/main/java/no/nav/tag/tiltaksgjennomforing/exceptions/IkkeTilgangTilDeltakerKode6Exception.java, src/main/java/no/nav/tag/tiltaksgjennomforing/exceptions/KanIkkeGodkjenneAvtalePåKode6Exception.java, src/main/java/no/nav/tag/tiltaksgjennomforing/exceptions/KanIkkeOppretteAvtalePåKode6Exception.java, src/main/java/no/nav/tag/tiltaksgjennomforing/exceptions/Kode6SperretForOpprettelseOgEndringException.java, src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggle.java, src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBrukerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleApiTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/BeslutterTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/VeilederTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/VtaoTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/caching/CachingConfigMockTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/caching/CachingConfigTest.java
featuretoggle sjekkForAdresseSperre for å unngå sjekk for kode6 eller ikke i ulike miljøer
=> feat. featuretoggle for å sjekke for kode6

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleSorterer.java
Etter ønske fra brukerstøttesak og samtale med Stine og Tonje
=> feat. sortering på deltaker etternavn

src/main/java/no/nav/tag/tiltaksgjennomforing/dev/DevController.java
* Opprett avtale som veileder
* Utfør oppfølgingsvarsling umiddelbart
=> Småfikser i DevController

src/test/java/no/nav/tag/tiltaksgjennomforing/TestDataGenerator.java
bruker bedriftnummere som matcher bedriftene i wiremock ved genererin…g av masse testdata
=> Wiremock bedriftnummer i labs

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
https://trello.com/b/LnAaxYzc/team-tiltak
=> feat. kreveroppfolging for nyetillskuddsperioder etter migrering fra arena

src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/aktsomhet/AktsomhetService.java
Ved henting av avtale med hentAvtale på avtalepart så fjernes deltaker fnr for avtalepart mentor.
Derfor måtte aktsomhet skrives om til å hente avtalen fra avtale-repository og heller gjøre tilgangssjekk utenom.
=> fix. aktsomhet for mentor

src/main/java/no/nav/tag/tiltaksgjennomforing/arena/admin/ArenaAdminController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaAgreementErrorCount.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaAgreementMigrationCount.java, src/main/java/no/nav/tag/tiltaksgjennomforing/arena/repository/ArenaAgreementMigrationRepository.java
* Hente statistikk for tiltakstype
* Resette kjøring som har failet
=> feat. admin-endepunkt for migrering

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
For å spore endringer i tilskuddsperioder for en avtale forsøker vi å legge til avtale-id i loggmeldingskontekst
=> Avtale-loggmeldinger har avtaleId i kontekst

src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/oppgave/LagGosysVarselLytter.java
Disse avtalene er allerede inngått i Arena og vi
trenger derfor ikke sende melding igjen.
=> fix. ikke send gosys varsler om inngått avtale når opphav er Arena

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java, src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/beregning/EndreTilskuddsberegning.java, src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/beregning/LonnstilskuddAvtaleBeregningStrategy.java, src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/beregning/VarigLonnstilskuddAvtaleBeregningStrategy.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java, src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddAvtaleBeregningStrategyTest.java
Bygget videre på @sindredl sin endring for langvarig lønnstilskudd: https://github.com/navikt/tiltaksgjennomforing-api/pull/1364
=> feat. endre prosentsats for varig lonnstilskudd

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/admin/AdminController.java
* Et admin-endepunkt for å løse en brukerstøttesak om å flytte alle avtaler som ligger på nedlagt enhet over på ny enhet.
=> feat. et admin-endepunkt for å oppdatere enhet

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/VtaoStrategy.java
virker å være problemer med VTAO  strategi for sjekk av hvilke felter som er påkrevd.
=> gjør felt-sjekk på lik måte som andre tiltakstyper

src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java, src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/FilterSok.java, src/main/resources/db/migration/common/V136__tidssoner_filter_sok.sql
* Flyway stoppet opp i deploy for prod pga for stor datamengde noe som gjorde at applikasjonen kræsjet. Derfor bør det lages et nytt felt for sist_sokt som blir migrert over.
=> fix. migrere til nytt felt med tidssone for filter-sok
