navikt/tiltaksgjennomforing-api

- pom.xml
- src/main/java/no/nav/tag/tiltaksgjennomforing/SwaggerConfig.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/TiltaksgjennomforingApplication.java
Legger inn støtte for swagger med springfox-swagger2. Rå copy/paste fra 
https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api
Dette funker tilsynelatende bra, og man kan bruke swagger-ui til å teste APIet med.
MEN det er foreløpig ingen sikkerhetsmekanismer her. Før dette går i prod bør vi vurdere hva som skal være eksponert og kanskje flytte ui til en url under internal.
> Legger til swagger

- src/main/resources/db/migration/V10__ny_tabell_bjellevarsel.sql
Legger denne endringen utenom kodeendring, slik at kodeendring eventuelt kan reverteres. Denne nye tabellen påvirker ikke andre data om den ikke tas i bruk.
> TAG-53: Ny tabell for bjellevarsel. 

- src/main/resources/db/migration/V10__ny_tabell_bjellevarsel.sql
Legger denne endringen utenom kodeendring, slik at kodeendring eventuelt kan reverteres. Denne nye tabellen påvirker ikke andre data om den ikke tas i bruk.
> TAG-53: Ny tabell for bjellevarsel

- src/main/java/no/nav/tag/tiltaksgjennomforing/CorrelationIdSupplier.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/integrasjon/CorrelationIdFilter.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/integrasjon/axsys/AxsysService.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/CorrelationIdSupplierTest.java
Filter som genererer ny correlationId ved hver request, slik at alle loggmeldinger blir logget med kallkjedeidentifikator. Bruker den samme id-en i kallet til Axsys.
> Logger med correlationId

- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/pilottilgang/AxsysService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/pilottilgang/TilgangUnderPilotering.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/ByEnhetStrategy.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggleConfig.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/pilottilgang/AxsysServiceTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/pilottilgang/TilgangUnderPiloteringTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/ByEnhetStrategyTest.java
Støtte for å bruke ByEnhet-strategien til unleash. 
Denne fungerer slik at en toggle blir `true` dersom innlogget veileder har tilgang til minst ett av kontorene som er definert i `byEnhet`-strategi på togglen i unleash. Veilederkontor blir slått opp gjennom axsysservice.
Har også lagt inn støtte for å benytte unleash til å styre pilottilgangen. Det er to toggler som styrer dette:
- _tag.tiltak.bruk.unleash.for.pilottilgang_ - angir om tilgangen skal styres gjennom unleash (hvis true) eller gjennom vault som tidligere (hvis false)
- _tag.tiltak.pilottilgang_ - om pilot er enablet eller ikke (brukes kun hvis togglen over er true). Pr nå inneholder denne alle brukere og nav-enheter som var lagt inn for preprod og prod i vault
> Unleash for pilottilgang

- src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggleConfig.java
Hadde glemt å faktisk ta i bruk den nye _ByEnhetStrategy_, så toggler som benyttet denne ble aldri evaluert riktig.
> Sørger for at Unleash tar hensyn til ByEnhetStrategy

- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/pilottilgang/TilgangUnderPilotering.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/metrikker/MetrikkRegistrering.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/pilottilgang/TilgangUnderPiloteringTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/metrikker/MetrikkRegistreringTest.java
Siden metrikk-logging logger ulikt dersom brukeren får pilottilgang pga. enkelt-ident vs brukere som får tilgang pga. kontor-tilgang, måtte jeg endre litt på hvordan dette settes opp. I stedet for én toggle som gir begge tilganger, brukes én toggle for ident-tilgang og en annen for kontor-tilgang - dermed blir det mulig å vite hva slags type tilgang brukeren får. Dette forutsetter at vi ikke blander sammen ulike strategier på togglene i unleash :)
> Deler opp tilgang for kontor vs. tilgang for ident for å kunne logge riktig

- src/main/java/no/nav/security/oidc/test/support/JwtTokenGenerator.java
- src/main/java/no/nav/security/oidc/test/support/spring/TokenGeneratorController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/TokenUtils.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/TokenUtilsTest.java
Enkel, men kanskje litt lite eksplisitt håndtering av kravet om innloggingsnivå 4 for sluttbrukere.
I stedet for å bruke `@ProtectedWithClaims` på controlleren har jeg lagt det inn i TokenUtils, som ikke vil "finne" en innlogget selvbetjeningsbruker med mindre det finnes et _acr-claim_ som er _Level4_
> TAG-512 Krever at selvbetjeningsbrukere er på nivå 4

- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggingService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/TokenUtils.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/InternalAvtaleController.java
- src/main/resources/config/application-dev.yaml
Fjernet en linje som ga 500-feil i stedet for 403 ved feil servicebruker.
Går tilbake til å bruke `@ProtectedWithClaims`-annotasjonen på controller for å sikre at vi har en systembruker. Det ser ut som dette fungerer som det skal, men vil likevel gi 403 dersom man _både_ har en systembruker og et brukertoken (som cookie) på requesten. Dette er fordi `TokenUtils` kun returnerer én bruker, og vil ta servicebruker til slutt. ~~Vi kan vurdere å endre på rekkefølgen her, slik at systembrukere hentes først, eller evt. håndtere bedre at det er flere tokens samtidig.~~ Har endret dette i 5aaa47d, slik at systembruker velges først dersom den eksisterer på requesten
Å bruke `@UnProtected` vil også fungere så lenge vi alltid sjekker systembruker eksplisitt i etterkant, men alle tilfeller av ugyldig …
> System-tilgangsstyring

- src/main/resources/config/application-preprod.yaml
- src/main/resources/config/application-prod.yaml
Samme endring er testet runtime i preprod og prod tidligere vha. miljøvariable. Det har løst ytelsesproblemene vi har sett. Legger denne konfigurasjonen nå i koden.
Ved idle bruker vi som før kun 1 connection, og det skal derfor ikke være sånn at vi okkuperer flere connections enn nødvendig på databaseclusteret.
> Øker maksimalantallet connections for CP

- pom.xml
- src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/database/JdbcConvertersConfiguration.java
I tillegg til tilpasninger til ny versjon av Spring Boot:
* Fjerner bean som ikke er nødvendig for å ha transaksjonsstøtte.
* Fjerner ubrukt maven-profil
> Oppdater til versjon 2.2.0 av Spring Boot

- pom.xml
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBruker.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetNavAnsatt.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetSelvbetjeningBruker.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtalePredicate.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java
- src/main/resources/db/testdata/V1000__testdata.sql
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtalePredicateTest.java
To nye operasjoner, en som henter avtaler for veileder ut fra url-parameter og en som henter avtaler for innlogget veileder ut fra innloggingstoken.
> TAG-779 Hente avtaler for veileder

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/GodkjentPaVegneGrunn.java
- src/main/resources/db/migration/V15__godkjent_pa_vegne_av_inn_i_avtaletabell.sql
- src/main/resources/db/testdata/V1000__testdata.sql
Fjerner en-til-en-relasjon og embedder feltene inn i avtale-tabellen. Oppførselen er ellers lik.
Formålet er enklere Hibernate-mapping.
Etter at denne er verifisert OK gjøres sletting av tabell: https://github.com/navikt/tiltaksgjennomforing-api/pull/105
> Flytter felter fra godkjent_pa_vegne_grunn inn i avtale-tabell

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Arbeidstrening.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtalepart.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Lonnstilskudd.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoering.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapper.java
- src/main/resources/db/migration/V16__legg_til_sist_endret_slett_versjon.sql
- src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtalepartTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/VeilederTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapperTest.java
Det blir begrepskollisjon når vi innfører versjonering av avtale. Så for å forenkle endrer jeg til timestamp til optimistisk lås, i stedet for versjonummer. I tillegg vil vi kunne bruke feltet `sistEndret` til noe fornuftig, for eksempel til å sortere avtaleoversikten.
PR i frontend: https://github.com/navikt/tiltaksgjennomforing/pull/203
Frontend og backend må deployes samtidig.
> Sist endret timestamp som optimistisk lås i stedet for versjonsnummer

- src/main/resources/db/migration/V17__sist_endret_defaultverdi.sql
Kolonnen brukes bare til optimistisk lås per i dag, og er derfor ikke synlig. På et senere tidspunkt kan det være aktuelt å vise tidspunktet. For avtaler som allerede er inngått, og som ikke endres senere, vil nok opprettet tidspunkt være en bedre default.
> Endrer defaultverdi på sist_endret til opprettet_tidspunkt

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/PersondataService.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/persondata/PersondataServiceTest.java
- src/test/resources/mappings/pdl_gradering.json
Etter samtale med PDL-teamet, viser det seg at responsen er litt annerledes enn først antatt. Vi tar derfor nå høyde for at responsen ser slik ut når man ikke har noen gradering:
```
{
"data": {
"hentPerson": {
"adressebeskyttelse": []
}
}
}
```
Har en pending task på å refaktorere PersondataService ytterligere, som bla. innebærer å skrive om til å bruke variables i GraphQL-spørringen.
> Tar hoyde for at adressebeskyttelse array er tom ved ugradert person

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java
Endres fordi avtalen skal kunne forlenges til 1 år, men 1,5 år i enkelte tilfeller. Bruker 1,5 år som grense siden vi ikke klarer å skille mellom når det skal være 1 år og når det skal være 1,5 år.
> Endre maks varighet fra 3 til 18 maneder

- pom.xml
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggleService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/Adressebeskyttelse.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/HentPerson.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/Navn.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/NavnFormaterer.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/PdlRequest.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/PdlRespons.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/PersondataService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/persondata/Variables.java
- src/main/resources/pdl/hentPerson.adressebeskyttelse.graphql
- src/main/resources/pdl/hentPerson.navn.graphql
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/persondata/NavnFormatererTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/persondata/PersondataServiceTest.java
- src/test/resources/mappings/pdl_gradering.json
Henter navn fra PDL og setter `deltakerFornavn` og `deltakerEtternavn` når avtalen opprettes.
Fra PDL kommer alt i store bokstaver. Jeg formaterer navnet med `WordUtils` fra Apache Commons, som legger på stor bokstav etter mellomrom eller bindestrek.
> TAG-57 Preutfyll deltakernavn når avtale opprettes

- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/altinntilgangsstyring/AltinnTilgangsstyringService.java
Når man spør altinns reportee endepunkt om bedrifter en person kan representere gir de tydeligvis bare tilbake de 50 første. Lagt på queryParameter for øke dette til 500.
> Lagt til pagesize i Altinn-kall, stotter na opptil 500 org istedenfor 50

- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggingService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/altinntilgangsstyring/AltinnTilgangsstyringService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/AltinnTilgangsstyringServiceTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggingServiceTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java
- src/test/resources/mappings/altinn_tilgangsstyring.json
Kaster exception når altinn-kall feiler, istedenfor å bare returnere en tom liste med organisasjoner.
Tar imot innlogget-part cookien som settes i frontend når man logger inn og bruker denne til å kun kalle altinn når en arbeidsgiver er logget inn.
Kan sees i delvis sammenheng med https://github.com/navikt/tiltaksgjennomforing/pull/239 og bør deployes etter denne
> TAG-1046 Handtere Altinn-feil

- alerterator-prod.yaml
Peker alerterator bort fra tag-notifications over mot arbeidsgiver-notifications.
> Alerterator mot ny slack kanal

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/EndreAvtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStrategy.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoering.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapper.java
- src/main/resources/db/migration/V22__endre_stillingstype_til_stillingstittel.sql
- src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/journalfoering/AvtaleTilJournalfoeringMapperTest.java
Endret navn på databasefeltet `stillingtype` til `stillingstittel`. Den PR-en har direkte knytning til PR på frontend med samme navn. (https://github.com/navikt/tiltaksgjennomforing/pull/369)
> Endret navn pa databasefeltet stillingtype til stillingstittel

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/ArbeidstreningStrategy.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleInnhold.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/ArbeidstreningStrategyTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java
Lagt til `stillingstittel` som påkrevd felt i arbeidstrening. Henger sammen med frontend PR som gjør om steget Arbeidsoppgaver til Stilling og inkluderer Stillingstittel på lik linje med lønnstilskudd. (https://github.com/navikt/tiltaksgjennomforing/pull/373)
> TAG-1004 Arbeidsoppgaver til stilling arbeidstrening

- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetArbeidsgiver.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBruker.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBrukerController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetDeltaker.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetVeileder.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggingService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/veilarbabac/TilgangskontrollService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/veilarbabac/VeilarbabacClient.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtalerolle.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/BjelleVarselController.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/TestData.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBrukerTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggingServiceTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/TokenUtilsTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/veilarbabac/VeilarbabacClientTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java
Gjør om `InnloggetSelvbetjeningbruker` til `InnloggetDeltaker` og `InnloggetArbeidsgiver`, for å kunne gjøre mer spesifikke spørringer mot databasen og droppe `AvtaleRepository.findAll()`-kallet.
> Ytelseforbedring: hent alle avtaler

- src/main/resources/config/application-dev-fss.yaml
- src/main/resources/config/application-prod-fss.yaml
Altinn-rettigheter-proxy er nå tilgjengelig på gcp.
Vi har allerede byttet to applikasjoner over til gcp-versjonen uten problemer. Siden dere bruker altinn-rettigheter-proxy-klient, er det også mindre risiko, siden dere kaller altinn direkte ved problemer.
> Bruk gcp-versjon av altinn-rettigheter-proxy

- src/main/resources/config/application-dev-fss.yaml
- src/main/resources/varsler/opprettNyBeskjed.graphql
- src/main/resources/varsler/opprettNyOppgave.graphql
I forbindelse med en forenkling av produsent-apiet for notifikasjoner,
så ønsker vi å migrere alle over på det nye formatet, slik at vi kan
slette det gamle formatet.
Si bare i fra, så tester jeg i dev.
> Nyere versjon av notifikasjon-api

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/RegnUtTilskuddsperioderForAvtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/GjeldendeTilskuddsperiodeTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/RegnUtTilskuddsperioderForAvtaleTest.java
- Tilskuddsperioder er redusert fra 3mnd til maks 1mnd.
- Alltid splitting ved månedsskifte.
- Fristen fro å godkjenne/beslutte tilskuddsperioder er økt fra 1mnd frem i tid til 3mnd. Dette vil gi samme lengde på avholding av midler som før, siden hver tilskuddsperiode nå er 1mnd.
- Justert tester til å passe til logikk for 1 måneds perioder i steden for 3.
> Utlede 1 måned tilskuddsperioder i steden for 3.

- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggingService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtalepart.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddsperiodeConfig.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java
- src/main/resources/config/application-dev-fss.yaml
- src/main/resources/config/application-labs-gcp.yaml
- src/main/resources/config/application.yaml
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetBrukerTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleControllerTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtalepartTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/LonnstilskuddStartOgSluttDatoStrategyTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/MentorStrategyTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/RegnUtTilskuddsperioderForAvtaleTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/VeilederTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/enhet/VeilarbArenaClientTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/varsel/LagVarselFraAvtaleHendelserTest.java
- src/test/resources/config/application-local.yaml
Egen liste med pilotvirksomheter fra miljøvariabel. Brukes til å avgjøre om det skal generere tilskuddsperioder.
Brukes også til å avgjøre om en avtale skal settes til ingått eller ikke. for sommerjobb og pilotavtaler av typen lønnstilskudd vil det ikke bli inngått før beslutter har godkjent første tilskuddsperiode.
Vil nå være 2 muligheter for at det skal generes tilskuddsperioder:
```
tilskuddsperioder:
tiltakstyper: SOMMERJOBB
pilotvirksomheter: ${tiltaksgjennomforing.pilot.pilotvirksomheter}
```
Skrur i tillegg av generering av tilskuddsperioder på lønnstilskudd i dev som default, for å sjekke at det fungerer med ny toggle/miljøvariabel. Dette kan skrus på igjen senere.
> Miljøvariabel med orgnummere det skal opprettes tilskuddsperioder for

- src/main/java/no/nav/tag/tiltaksgjennomforing/datavarehus/DvhMeldingFilter.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/datavarehus/DvhMeldingProperties.java
- src/main/resources/config/application-dev-fss.yaml
- src/main/resources/config/application-prod-fss.yaml
- src/test/java/no/nav/tag/tiltaksgjennomforing/datavarehus/DvhMeldingFilterTest.java
Gjør om sjekk som avgjør om avtalehendelser skal til datavarehus elller ikke. Istedenfor å sjekke om tiltakstype er sommerjobb sjekkes det om avtalens tiltakstype finnes på en miljøvariabel på dvhMeldingFeatureProperties.
Lagt inn følgende:
Dev:
```
dvh-melding:
feature-enabled: true
tiltakstyper: SOMMERJOBB, MIDLERTIDIG_LONNSTILSKUDD, VARIG_LONNSTILSKUDD
```
Prod:
```
dvh-melding:
feature-enabled: true
tiltakstyper: SOMMERJOBB
```
> Lønnstilskudd til datavarehus i dev

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/SommerjobbStartOgSluttDatoStrategy.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/startOgSluttDatoStrategy/SommerjobbStartOgSluttDatoStrategyTest.java
Maks 4 uker varighet på sommerjobb.
Trekker i fra 1 dag på kalkuleringen, fordi vi regner fom og tom.
Eksempel:
7 dager (1 uke) x 4 = 28.
01.06 - 28.06 (28 dager / 4 uker).
Teller man 01.06.plusWekkes(4) ender man opp på 29.06. 29.06 er den første dagen i uke 5. Derfor må vi trekke fra 1 dag. Illustrert med kalender som viser en periode på 4 uker.
> Maks 4 uker varighet på sommerjobb.

- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/altinntilgangsstyring/AltinnTilgangsstyringProperties.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/altinntilgangsstyring/AltinnTilgangsstyringService.java
- src/main/resources/config/application-dev-fss.yaml
- src/main/resources/config/application-labs-gcp.yaml
- src/main/resources/config/application-prod-fss.yaml
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/AltinnTilgangsstyringServiceTest.java
- src/test/resources/config/application-local.yaml
- src/test/resources/mappings/altinn_10.json
- src/test/resources/mappings/altinn_20.json
- src/test/resources/mappings/altinn_ikke_treff.json
Altinn tilganger for `mentor` og `inkluderingstilskudd` er nå i prod hos altinn. Da kan vi begynne å hente inn disse for arbeidsgiver.
lagt inn mocking så man lokalt og på labs alltid har tilgang til disse også.
Opprettelse av inkluderingstilskudd for veileder er togglet bort med featureToggle på samme måte som med mentor.
Det er nå også lagt inn toggle på opprettelse for arbeidsgiver for både mentor og inkluderingstilskudd, fordi arbeidsgiver får lov til å opprette avtaler på de tiltakstypene de har tilgang på.
> Henting av Altinn tilganger for mentor og inkluderingstilskudd

- src/main/resources/config/application-dev-fss.yaml
- src/main/resources/config/application-prod-fss.yaml
I forbindelse med at Azure B2C ble skrudd av i loginservice,
så har audience endret seg. Ved å bruke audience fra environemnt-
variabler blir dette riktig. Selvbetjenings-autentisering har ikke
fungert i prod siden 19. mai.
Se tråd her: https://nav-it.slack.com/archives/C01DE3M9YBV/p1647867506386019
> Oppdater audience for loginservice.

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Beslutter.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java
Fiks for beslutter spørring ifbm. regel at tilskuddsperioder ikke kan godkjennes for neste år.
Omdefinerer hvor langt frem man skal lete for å finne ubehandlede tilskuddsperioder. Sjekker her på alle som har startdato frem til siste dagen i året.
> Beslutterspørring bugfiks

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/VeilederTest.java
Generer tilskuddsperioder ved overtagelse av avtale som er ufordelt.
Dette retter en feil som kunne skje hvis arbeidsgiver oppretter avtale, fyller ut alt, så overtar veileder og godkjenner.
Grunnen er at ved opprettelse av avtale for arbeidsgiver, settes ikke enhet oppfølging og kvalifiseringsgruppe. Lønnstilskuddprosent settes automatisk ut ifra kvalifiseringsgruppe på midlertidig lønnstilskudd.
> Generer tilskuddsperioder ved overtagelse av ufordelt avtale

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
lagt inn skip og limit på beslutter-endepunkt på samme måte som på avtaleoversikten, så vi har støtte for å hente litt og litt for å redusere tiden det tar å laste store mengder.
> Skip og limit på beslutteroversikten

- src/test/resources/config/application-dockercompose.yml
- src/test/resources/config/application-local.yaml
Appen som brukes for å opprette innlogginger
i test kjørte tidligere på labs, men har nå
blitt migrert til dev-gcp.
> Endre url for tiltak-fakelogin

- .github/workflows/bygg-og-deploy-dev.yml
- .github/workflows/bygg-og-deploy-master.yml
setup-jave har en cache-option, så vi
behøver ikke en separat action for det.
Oppgradert til setup-java@v3 for å bli
kvitt en deprecation warning
> Oppgrader workflows

- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/abac/TilgangskontrollServiceImpl.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/abac/adapter/AbacAdapter.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/IntegrasjonerMockServer.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/abac/adapter/AbacAdapterTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/caching/CachingConfigMockTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/caching/CachingConfigTest.java
Dersom kall til abac feiler (feks timeout), vil vi fange opp feilen, logge og deretter lagre at bruker ikke har tilgang i cachen!
Denne endringen sørger for at feil fra Abac fortsatt teller som "ikke tilgang", men vi lagrer kun i cache dersom kallet til abac er vellykket.
> Ikke cache feil fra Abac

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java
Vi hadde en feil ved kombinasjonen filter på status og ulike sorteringer. Status er filtering i java-kode og ikke databasen. Da må man hente en stor page fra basen for å få all data. Dette ble ikke gjort i alle de ulike kombinasjonene av filter.
> FIkset sortering på status. Hentet ikke all data i en page

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Arbeidsgiver.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtalepart.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Beslutter.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Deltaker.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Mentor.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/DeltakerTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/MentorTest.java
Tidligere "skjulte" vi data i listevisning (søk) ved å sette data i Entities til "null". Dette hade noen uventede side effects. Som at data ble slettet fra databasen.
Skjuler nå data i "DTO" som brukes til frontend.
> Skjuler data i listevisning lenger ut i stakken. I dto til frontend

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtalePredicate.java
manglet erUfordelt i metode for å generere hash - førte til falske kollisjonsmeldinger
> manglet erUfordelt i metode for å generere hash

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleSorterer.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Beslutter.java
Lagt til så man kan sortere på lavest og høyest på de ulike sorteringskolonnene.
[https://github.com/navikt/tiltaksgjennomforing/pull/1184](https://github.com/navikt/tiltaksgjennomforing/pull/1184)
> Sortering på lavest og høyest på sorteringKolonne

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
Alle andre filtrer sender også med DESC elr ASC siden det styres med pilene
Setter verdien till DESC da sistEndret kan sendes uten rettning
[https://github.com/navikt/tiltaksgjennomforing/pull/1188](https://github.com/navikt/tiltaksgjennomforing/pull/1188)
> Endret til defaultverdi til DESC for sistEndret

- nais/dev-fss.yaml
- nais/dev-gcp-labs.yaml
- nais/prod-fss.yaml
Error: Status: failure: nais.io/v1alpha1, Kind=Application, Namespace=arbeidsgiver, Name=tiltaksgjennomforing-api: updating resource: strict decoding error: | unknown field spec.team
| The field might be misspelled, incorrectly indented, or unsupported. Fields are case sensitive. | Please verify your resource against the reference documentation at https://doc.nais.io/nais-application/application/ (total of 1 errors)
> fix. Fjerne spec.team fram nais yaml

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Veileder.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/enhet/EnhetController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/enhet/Norg2Client.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/caching/CachingConfigMockTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/caching/CachingConfigTest.java
Degrader logging for henting av enhet i Norg2 til warn. Dette blir nå validert i frontend og håndtert der.
> fix. Degradere logging til warn

- src/main/resources/config/application-dev-fss.yaml
Slutter også å bruke Vault for å lagre jdbc-url'en, da denne ikke inneholder passord.
> Endre path til database i dev

- src/main/java/no/nav/tag/tiltaksgjennomforing/datavarehus/DvhStatusendringJobb.java
- src/main/resources/config/application.yaml
- src/test/resources/config/application-dockercompose.yml
- src/test/resources/config/application-local.yaml
Øker frekvensen på den skedulerte jobben for å se etter statusendring på meldinger til datavarehus fra 10 minutter til 2 timer.
Dette trengs trolig ikke kjøres oftere enn 1 gang om dagen, statusendringer som ikke fanges opp av domeneeventer, så langt jeg kan skjønne, skjer kun ved datoendringer.
> øker til hver andre time på dvh statusendring jobb

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AlleredePaaTiltakRequest.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
For å unngå fødselsnr i URLer oppretter
vi et nytt post-endepunkt som skal erstatte
get-endepunktet for å sjekke om en deltaker
er på tiltak.
> Nytt post-versjon av endepunkt

- src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/Varsel.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/varsel/VarselFactoryTest.java
Vis periode (dato fra og til) det gjelder i varselloggen når beslutter godkjenner tilskuddsperiode. Det var forvirrende tidligere da veileder/beslutter ikke kunne se hvilken periode det gjelder i hendelsesloggen.
> Vis periode(dato fra og til) for godkjent tilskuddsperiode i hendelseslogg når beslutter godkjenner 

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/HendelseType.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/events/ArbeidsgiversGodkjenningOpphevetAvVeileder.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/datadeling/AvtaleHendelseLytter.java
Domain event og hendelse på kafka for hendelsen arbeidsgivers godkjenninger opphevet av veileder. For bruk i notifikasjonsapp, for å slippe å sjekke om arbeidsgiver hadde godkjent.
> opphevet arbeidsgivers godkjenninger

- pom.xml
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/ArbeidsgiverTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/TestData.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/ByOrgnummerStrategyTest.java
altinn-rettigheter-proxy-klient 2.0.1 hadde en avhengighet til com.github.kittinunf.fuel 2.2.1 som har blitt avpublisert.
> fix. Oppgrader altinn-rettigheter-proxy-klient

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/InkluderingstilskuddStrategy.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/satser/Sats.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/satser/SatsPeriodeData.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/beregning/VTAOLonnstilskuddAvtaleBeregningStrategy.java
I stedet for å opprette en databasetabell
for satser, som medfører en stor refaktorering
av løsningen for å kunne ta i bruk, kan vi bruke
singleton-objekter i stedet.
Ulempen her er at vi må redeploye appen for å
få inn nye års satser, men fordelen er at objektene
gjør oppslag litt enklere, slik vi ser i endringen
i InkluderingstilskuddStrategy-klassen.
> Lite-versjon av satsetabell

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java
I stedet for at frontenden må drive med
tidsmatematikk for å avgjøre om beslutter
kan trykke på en knapp, kan frontenden heller
se på et boolean-flagg "kanBehandles".
Denne fasiliterer følgende frontend-endring: https://github.com/navikt/tiltaksgjennomforing/pull/1261
> Ny jsonproperty: kanBehandles

- nais/prod-fss.yaml
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/ArenaOrdsClient.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/ArenaOrdsFnrRequest.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/ArenaOrdsFnrResponse.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/configuration/ArenaKafkaConsumerConfig.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/job/ArenaAgreementJob.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/job/ArenaEventProcessingJob.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/kafka/ArenaKafkaConsumer.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/event/ArenaEventStatus.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/repository/ArenaEventRepository.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaEventProcessingJobService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaEventProcessingService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/TiltakgjennomforingArenaEventProcessingService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/FeatureToggle.java
Denne endringen gjør at vi kun lagrer meldinger fra Arena Kafka og deretter prosseserer dem i en egen jobb. Dette vil gjøre at vi får mindre feil og at ting går litt smidigere.
ORDS tjenesten for Arena ble også fikset - vi sendte ikke korrekt request. 
Til slutt resetter group-id for lesing.
> feat. oppdatere henting av Arena data til skyggetabeller

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/jobber/PabegynteAvtalerRyddeJobb.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/service/PabegynteAvtalerRyddeService.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/service/PabegynteAvtalerRyddeServiceTest.java
* Egen service med Transactional
* Kjøre jobben 10 over 12 - 5 min etter status jobben
* Bruke nytt status-felt for å hente avtaler fra databasen
> feat. forbedring av ryddejobb

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java
- src/main/resources/db/migration/V111__gjeldende_tilskuddsperiode.sql
For å enklere kunne filtrere på relevante avtaler må vi kunne vite hvilken tilskuddsperiode som er "gjeldende" til enhver tid.
På samme måte som vi har en "gjeldende avtaleinnhold" så vil vi også ha en "gjeldende tilskuddsperiode".
Foreløpig vil gammel måte å hente ut gjeldende periode på bli brukt, og så logger vi et varsel for alle
eventuelle avvik som dukker opp før vi er komfortable med at migreringen har blitt robust nok.
> Legg til felt for gjeldende tilskuddsperiode

- src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/beregning/VTAOLonnstilskuddAvtaleBeregningStrategy.java
Forkortinger som kortet ned en vtao-periode ble ikke gitt et beløp for perioden, og ville feile med nullpointer.
> Overstyr beregnTilskuddsbeløpForPeriode for VTAO

- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaAgreementMigration.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaAgreementProcessingService.java
- src/main/resources/db/migration/V116__ny_primary_key_arena_agreement_migration.sql
Det kan være flere instanser av tiltaksgjennomføringer, derfor er det litt dumt at det blir brukt som primary key.
> feat. ikke bruk tiltakgjennomforingId som primary key i ArenaAgreementMigration

- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/repository/ArenaAgreementMigrationRepository.java
I Q0 begynte jobben å gå treigere etterhvert fordi det ble litt for mange avtaler å prosessere samtidig. Siden vi skal kjøre migrering parallelt med annen vanlig drift er det derfor lurt å sette ned størrelsen på antall vi kjører per jobb.
Løpetid på jobben vil bli ca 1 time og 15 min med denne endringen.
> feat. kjøre mindre batcher for migreringsjobb

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AlleredeRegistrertAvtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleMinimalListevisning.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/BeslutterOversiktDTO.java
Dersom informasjonen til en deltaker dukker opp
i en listevisning, skal ikke dette medføre logging til arcsight.
Formålet med auditlogging er å logge oppslag på en spesifikk bruker, men listeoppslagene vil skape
unødvendig støy.
Dette er beskrevet i etterlevelseskrav K253.1
> Ikke auditlogg listeoppslag

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleMinimalListevisning.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/BeslutterOversiktDTO.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditElement.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditEntry.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditLoggingAspect.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AuditerbarEntitet.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/auditing/AvtaleMedFnrOgBedriftNr.java
Formålet med endringen er å kunne spore unike oppslag på en deltaker sin informasjon.
Hvorfor behøver vi den informasjonen? Fordi auditlogging av oppslag skal kun skje dersom en avtale ikke har endret seg! Men det medfører at auditlogging-appen vår vet at et oppslag er unikt.
> Inkluder "sistEndret" og "id" i auditlogging

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/HendelseType.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/oppfolging/OppfølgingVarsleJobb.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/LagVarselFraAvtaleHendelser.java
Gjøres ved å opprette et "varsel" uten bjelle og
som allerede er lest.
> Logg at oppfølging av tiltak er utført

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleSorterer.java
- src/main/resources/config/application.yaml
Viser avtaler med oppfolgingVarselSendt overst på default og når man sorterer på status desc
[Trello ](https://trello.com/c/EtWBrbF6/1710-oppf%C3%B8lging-kreves-status-m%C3%A5-ha-h%C3%B8y-prioritet-i-oversiktssiden)
> Feat. sortering på oppfolging kreves

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleSorterer.java
Ved sortering på felter som har lik verdi blir ordren ustabil slik at databasen ikke vet hvilke felt som har blitt sortert først eller sist. Dette kan føre til at listen inneholder duplikater.
Denne endringen legger til en seed, som bli id - avtale id eller refusjon id som skal beholde korrekt ordre ved sortering og paginering
> fix. fikse stabilitet i sortering

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java
Foreslått feilkode er den samme som "for tidlig",
ettersom beløp gjerne er null fordi at sats for
neste år mangler
> Ikke lov å behandle tilskuddsperioder uten beløp

- src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/cache/CacheConfig.java
- src/main/resources/config/application.yaml
I loggene våre logges blant annet denne warning'en:
The cache 'pdl_cache' is not recording statistics. No meters except 'cache.size' will be registered. Call 'Caffeine#recordStats()' prior to building the cache for metrics to be recorded.
For å logge cache-metrikker legger vi til recordStats i metoden som bygger cachene våre.
> Fiks varsel om manglende cache-statistikk

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriodeRepository.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/admin/AdminController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/satser/Sats.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/VtaoTest.java
Hvert år får vi ny VTAO-sats, som vi per dags dato hardkoder inn. Men når vi legger til ny sats vil tilskuddsperioder som allerede er generert ikke bli oppdatert med nye beløp.
Derfor legger vi inn et admin-endepunkt som kan kjøres for å etterfylle beløp på tilskuddsperiodene.
På sikt kan vi kanskje finne en bedre rutine på dette, men dette er noe som skal skje en gang i året, så denne rutinen er kanskje ikke ekstremt smertefull.
> Rutine for oppdatering av VTAO-tilskudd

- src/main/java/no/nav/tag/tiltaksgjennomforing/TiltaksgjennomforingConfiguration.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/hendelse/HendelseAktivitetsplanClient.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/hendelse/HendelseAktivitetsplanIdRequest.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/client/ords/ArenaOrdsClient.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaAgreementProcessingService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/admin/AktivitetsplanAdminController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/enhet/Norg2Client.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/featuretoggles/enhet/AxsysService.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/sts/STSClient.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/infrastruktur/sts/StsConfiguration.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/leader/LeaderPodCheck.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/okonomi/KontoregisterServiceImpl.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/orgenhet/EregService.java
Prometheus-metrikkene våre lagrer url'en som rest-klienten kaller som en "uri-tag" i request-metrikker, som betyr at når vi bygger strings som feks:
http://EREG_URL/12345678
vil det være en linje per bedrift vi slår opp på. I verste fall kan vi også logge fødselsnumre i metrikkene våre.
Vi kan endre til å bruke uri-variabler slik:
http://EREG_URL/{bedriftNr}
og da vil Prometheus logge alle oppslag mot ereg som bare en metrikk.
> Bruk uri-variabler i utgående http-requests

- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaAgreementMigration.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaMigrationAction.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/models/migration/ArenaMigrationProcessResult.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/arena/service/ArenaAgreementProcessingService.java
- src/main/resources/db/migration/common/V126__arena_migrering_feilmelding.sql
Lagre feilmeldinger ved migrering i databasen. Da blir det enklere ved oppslag å se hva som har skjedd og å dra ut statisikk i motsetning til å hente fra loggene i tillegg kan det lagres flere typer feilmelding ved å bruke string istedenfor å bruke ArenaAgreementAction. Actions var aldri ment til bruk for feilmeldinger.
> feat. lagre feilmeldinger ved migrering i databasen

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Avtale.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/EndreAvtale.java
Ikke generer nye tilskuddsperioder for vtao ved endring av avtale dersom det ikke er nødvendig. Databasetransaksjonen for å skrive disse tar for mye tid i produksjon.
> fix. ikke generer nye tilskuddsperioder for vtao ved endring av avtale

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java
Vi gjør allerede en sjekk på status og decision date i spørringen, derfor er det ikke nødvendig å gjøre denne ved join. Det ender bare i at løpenummer 1 aldri vises.
> fix. alltid vis løpenummer 1 for besluttere

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleUtlopHandling.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/service/PabegynteAvtalerRyddeServiceTest.java
* En del av avtalene vi henter fra Arena kommer til å utgå midt på sommeren. Derfor legger vi inn en sperre slik at disse avtalene ikke blir ryddet før tidligest 1 september.
> feat. ikke rydd bort vtao-avtaler fra Arena før etter sommeren

- src/main/resources/db/migration/common/V134__tidssoner_inkl_tilskudd_og_maal.sql
> fix. instant og tidssoner for inkl.tilskuddutgifter og mål

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/TilskuddPeriode.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/tilskuddsperiode/TilskuddsperiodeGodkjentMelding.java
- src/main/resources/db/migration/common/V135__tidssoner_tilskuddsperioder.sql
> fix. instant og tidssoner for tilskuddsperioder

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/FilterSok.java
- src/main/resources/db/migration/common/V136__tidssoner_filter_sok.sql
> fix. instant og tidssoner for filtersøk

- src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/Sms.java
- src/main/resources/db/migration/common/V137__tidssoner_sms.sql
> fix. instant og tidssoner for sms

- src/main/java/no/nav/tag/tiltaksgjennomforing/sporingslogg/Sporingslogg.java
- src/main/resources/db/migration/common/V138__tidssoner_sporingslogg.sql
> fix. instant og tidssoner for sporingslogg

- src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/Varsel.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/varsel/VarselRespons.java
- src/main/resources/db/migration/common/V139__tidssoner_varsel.sql
> fix. instant og tidssoner for varsel

- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Arbeidsgiver.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleController.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepository.java
- src/main/java/no/nav/tag/tiltaksgjennomforing/avtale/Mentor.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/autorisasjon/InnloggetArbeidsgiverTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/ArbeidsgiverOgMentorAvtalerEldreEnn12UkerIntegrasjonTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/ArbeidsgiverTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/AvtaleRepositoryTest.java
- src/test/java/no/nav/tag/tiltaksgjennomforing/avtale/MentorTest.java
* For en del bedrifter tar det alt for lang tid å hente avtalene som vises på min-side-arbeidsigver.
En av grunnene er at vi ikke har hatt noe begrensning på henting av eldre avtaler. Derfor er det lurt å ha samme begrensning som vi har for oversikten.
> fix. ikke hent eldre avtaler for min-side-arbeidsgiver
